### ISSUE TITLE
Dataset identifier gets mixed up when a template is involved

### ISSUE THREAD

**Issue by jennet** [DataDock/datadock#148]
This might be due to the use of a template for the upload, but the identifiers for the resources in a dataset don't match the URI chosen during the upload.

https://datadock.io/datadockdemo/police/page/dataset/stopAndSearchMetropolitanPoliceOctober2018.html#/explore

**Comment by jennet** [comment]
Right seems like there's two things to check out:

 - the folders in GitHub created for resources should match the last segment of the URI of the dataset identifier (they currently use the CSV filename)
- do uploads published using a template correctly use the new dataset identifier.

In the police repo used in the link above, both November and October were created using a template, but November used a record identifier using "Template Pattern" whereas October was edited to use "Row Number"

This could be the expected behaviour of "template pattern" but as I hadn't changed the original from "Row Number" I didn't spot that I needed to change it manually back to "Row Number" for subsequent uploads.

**Comment by jennet** [comment]
This does seem to be linked to the templating implementation as this recent upload of Locks from the Canals and Rivers Trust (no template used) seems as expected https://datadock.io/datadockdemo/canals-and-rivers/page/dataset/locks.html#/ld

**Comment by kal** [comment]
@jennet - was the template that you used an old template that predates the 0.5.0 release? That was when I fixed #126 by changing the way that aboutUrl is stored in the template to use a relative path. This means that when you use an old template that has a full URL in it, it doesn't match any of the options for the identifier drop-down and so it adds the "Template pattern" option. I think that is why the identifiers aren't working as expected.

I have added a fix for setting the datasetId correctly, the metadata editor now applies the title-to-datasetId mapping function on load as well as when you change the title. This will ensure that the datasetId gets updated if you load a template that has a predefined title in it.

**Comment by jennet** [comment]
@kal No this was totally fresh on the demo site - no old templates. :/

**Comment by jennet** [comment]
I've checked this and there's still a problem. I'll try and clarify (also I'm happy to keep this one assigned to me)

Steps to reproduce:

1. Select spreadsheets which suit templating (e.g. a few months of downloads from police.data.uk)
2. Upload the first spreadsheet 
    * Choose a title (this updates the dataset identifier)
    * Add small description, license, tags etc
    * **Select Row Number for resource identifier construction** (this step is important)
    * Check datatypes
    * Customise predicates
    * **Select Save As Template** (also important)

This converts and pushes to GH. Everything looks OK (aside from the fact that I feel that the resources should really all be pushed to GH in a directory that matches the last segment of the dataset identifier, rather than the CSV filename, but that's less important)

3. Return to DataDock dashboard.
4. Go to Template Library
5. Choose the template created with the last upload
6. Select a different month's data to upload
    * Change the title (therefore the dataset identifier)

The expected behaviour would be to be able to just change a title and then upload with no problems. However, the editor has preselected the "Template pattern" for resource identifiers. If this is left selected...

7. Hit Publish

There is no unique ID on these records, so the fact it uses row numbers means that the resources are merged together from different sets. See: https://datadock.io/jennet/ubiquitous-train/page/resource/201711AvonAndSomersetStopAndSearchcsv/row_1.html

(Notice the resource URLs are still under a CSV filename on GH. We should decide whether this is even an issue or expected behaviour and separate out from this issue if necessary)
----

If you manually change a "use template" upload to use Row Number. Then everything is OK. But a user is not going to know to do that. We need to not pre-select this option if the choice was "Row Number" as that just won't work as expected with templates (as far as I can figure)

cc @kal

**Comment by jennet** [comment]
Amended JS so that it does add the "Template Pattern" option to the row identifier drop down, but _if_ the template's `aboutUrl` ends with `row_{_row}` then it does not preselect it for the user.

![image](https://user-images.githubusercontent.com/4940135/55685693-1c16f380-5951-11e9-8056-e67ee1b3ad44.png)

**Comment by jennet** [comment]
Leaving this issue open so that we can discuss it before publishing the next release
